#!/usr/bin/env python3

import colors as c

print(c.clear)
title = format('''
    _____________  ___________                 ______________________________________________________   __
    ___  __/__  / / /__  ____/                 ___  __ \__    |__  /___  /___    |__  __ \___  _/__  | / /
    __  /  __  /_/ /__  __/                    __  /_/ /_  /| |_  / __  / __  /| |_  / / /__  / __   |/ / 
    _  /   _  __  / _  /___                    _  ____/_  ___ |  /___  /___  ___ |  /_/ /__/ /  _  /|  /  
    /_/    /_/ /_/  /_____/                    /_/     /_/  |_/_____/_____/_/  |_/_____/ /___/  /_/ |_/   

        
''')
print(title)

print("You wake up and get out of bed.  You look at your nighttable and gaze at a small sheet with three small colored boxes.  Today is the day you get your new dental fillings.  You have to choose between three colors: gold, silver, and copper.  Which do you choose?")
fillings = input("> ")
if fillings == "gold":
    print("Cool")
elif fillings == "silver":
    print("Great")
elif fillings == "copper":
    print("Amazing")
else:
    print("Fail")
