#!/usr/bin/env python3

import colors as c

# attacker's stats

print(c.clear)
print("Welcome to the Fire Emblem Battle Calculator!")
print("Please enter the attacker's stats.")
attacker_name = input("Attacker's name > ")
attacker_current_hp = int(input("Attacker's current HP > "))
attacker_max_hp = int(input("Attacker's max HP > "))
attacker_exp = int(input("Attacker's current EXP > "))
attacker_level = int(input("Attacker's level > "))
attacker_attack = int(input("Attacker's Attack > "))
attacker_magic = int(input("Attacker's Magic > "))
attacker_skill = int(input("Attacker's Skill > "))
attacker_luck = int(input("Attacker's Luck > "))
attacker_speed = int(input("Attacker's Speed > "))
attacker_defense = int(input("Attacker's Defense > "))
attacker_resistance = int(input("Attacker's Resistance > "))
attacker_weapon_type = input("Attacker's weapon type > ")
attacker_weapon_uses = int(input("Attacker's weapon's remaining uses > "))
attacker_weapon_might = int(input("Attacker's weapon's Might > "))
attacker_weapon_hit = int(input("Attacker's weapon's Hit % > "))
attacker_weapon_crit = int(input("Attacker's weapon's Critical Rate > "))
attacker_weapon_range = input("Attacker's weapon's Range > ")
attacker_weapon_effect = input("Attacker's weapon's added effect(s) > ")

# attacker's attack type (physical or magical)

if attacker_weapon_type == "sword":
    attacker_might = attacker_attack
elif attacker_weapon_type == "lance":
    attacker_might = attacker_attack
elif attacker_weapon_type == "axe":
    attacker_might = attacker_attack
elif attacker_weapon_type == "bow":
    attacker_might = attacker_attack
elif attacker_weapon_type == "beaststone":
    attacker_might = attacker_attack
elif attacker_weapon_type == "dragonstone":
    attacker_might = attacker_attack
elif attacker_weapon_type == "tome":
    attacker_might = attacker_magic

# Defender's stats

print("Please enter the defender's stats.")
defender_name = input("Defender's name > ")
defender_current_hp = int(input("Defender's current HP > "))
defender_max_hp = int(input("Defender's max HP > "))
defender_exp = int(input("Defender's current EXP > "))
defender_level = int(input("Defender's level > "))
defender_attack = int(input("Defender's Attack > "))
defender_magic = int(input("Defender's Magic > "))
defender_skill = int(input("Defender's Skill > "))
defender_luck = int(input("Defender's Luck > "))
defender_speed = int(input("Defender's Speed > "))
defender_defense = int(input("Defender's Defense > "))
defender_resistance = int(input("Defender's Resistance > "))
defender_weapon_type = input("Attacker's weapon type > ")
defender_weapon_uses = int(input("Attacker's weapon's remaining uses > "))
defender_weapon_might = int(input("Attacker's weapon's Might > "))
defender_weapon_hit = int(input("Attacker's weapon's Hit % > "))
defender_weapon_crit = int(input("Attacker's weapon's Critical Rate > "))
defender_weapon_range = input("Attacker's weapon's Range > ")
defender_weapon_effect = input("Attacker's weapon's added effect(s) > ")

# Defender's attack type (physical or magical) and attacker's defense type (physical or magical)

if defender_weapon_type == "sword":
    defender_might = defender_attack
    attacker_defense_power = attacker_defense
elif defender_weapon_type == "lance":
    defender_might = defender_attack
    attacker_defense_power = attacker_defense
elif defender_weapon_type == "axe":
    defender_might = defender_attack
    attacker_defense_power = attacker_defense
elif defender_weapon_type == "bow":
    defender_might = defender_attack
    attacker_defense_power = attacker_defense
elif defender_weapon_type == "beaststone":
    defender_might = defender_attack
    attacker_defense_power = attacker_defense
elif defender_weapon_type == "dragonstone":
    defender_might = defender_attack
    attacker_defense_power = attacker_defense
elif defender_weapon_type == "tome":
    defender_might = defender_magic
    attacker_defense_power = attacker_resistance

# Defender's defense type (physical or magical)

if attacker_weapon_type == "sword":
    defender_defense_power = defender_defense
elif attacker_weapon_type == "lance":
    defender_defense_power = defender_defense
elif attacker_weapon_type == "axe":
    defender_defense_power = defender_defense
elif attacker_weapon_type == "bow":
    defender_defense_power = defender_defense
elif attacker_weapon_type == "beaststone":
    defender_defense_power = defender_defense
elif attacker_weapon_type == "dragonstone":
    defender_defense_power = defender_defense
elif attacker_weapon_type == "tome":
    defender_defense_power = defender_resistance

# Battle Formulas

# Number of Attacks

if attacker_speed >= defender_speed + 5:
    attacker_attack_times = 2
    defender_attack_times = 1
elif defender_speed >= attacker_speed + 5:
    attacker_attack_times = 1
    defender_attack_times = 2
else:
    attacker_attack_times = 1
    defender_attack_times = 1

# Hit Rate

attacker_hit_rate = attacker_weapon_hit + attacker_skill * 2 + attacker_luck / 2
defender_hit_rate = defender_weapon_hit + defender_skill * 2 + defender_luck / 2

# Evade

attacker_evade = attacker_speed + attacker_luck / 2
defender_evade = defender_speed + defender_luck / 2
