#!/usr/bin/env python3

import colors as c

# Intro

title = format('''
  ,                              _            _                                          ____               
 /|   |                         (_|   |_/    | |                o                       (|   \             |
  |___|  __,    _    _            |   | __,  | |  _   _  _  _|_     _  _    _   ,        |    | __,        |
  |   |\/  |  |/ \_|/ \_|   |     |   |/  |  |/  |/  / |/ |  |  |  / |/ |  |/  / \_     _|    |/  |  |   | |
  |   |/\_/|_/|__/ |__/  \_/|/     \_/ \_/|_/|__/|__/  |  |_/|_/|_/  |  |_/|__/ \/     (/\___/ \_/|_/ \_/|/o
             /|   /|       /|                                                                           /|  
             \|   \|       \|                                                                           \|  


''')

print(c.clear)
print(title)
continue1 = input("> ")
print(c.clear)

# Riley

riley = format('''
Dear Sisbo,

Happy Valentines Day!  Thanks for always being so much fun to play with!

Love,
Brobo
''')

print(riley)
continue2 = input("> ")
print(c.clear)

# Mamo

mamo = format('''
Dear Mamo,

Happy Valentines Day!  Thanks for always being there to help!

Your loving son,
Rees
''')

print(mamo)
continue3 = input("> ")
print(c.clear)

# Fabo

fabo = format('''
Dear Fabo,

Happy Valentines Day!  Thanks for working hard so we can have a good life!

Your loving son,
Rees
''')

print(fabo)
continue4 = input("> ")
print(c.clear)

# Spheal

spheal = format('''
Dear Spheal,

Happy Valentines Day!  Thanks for being a cool dude.

Your sworn enemy,
Overlord Jerkface
''')

print(spheal)
continue5 = input("> ")
print(c.clear)

# Heart

heart = format('''

       @@@@@@           @@@@@@
     @@@@@@@@@@       @@@@@@@@@@
   @@@@@@@@@@@@@@    @@@@@@@@@@@@@@
  @@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
      @@@@@@@@@@@@@@@@@@@@@@@@@@@
        @@@@@@@@@@@@@@@@@@@@@@@
          @@@@@@@@@@@@@@@@@@@
            @@@@@@@@@@@@@@@
              @@@@@@@@@@@
                @@@@@@@
                  @@@
                   @

''')

print(heart)
